[package]
name = "flipkart_scraper"
description = "Scrape Flipkart product details"
version = "0.1.141"
edition = "2021"
license = "GPL-3.0"
repository = "https://github.com/dvishal485/flipkart-scraper"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib"]

[features]
default = ["serde", "wasm_parser"]
fetch = ["reqwest"]
wasm_parser = ["serde-wasm-bindgen", "wasm-bindgen", "serde"]

[dependencies]
eyre = "0.6.12"
scraper = "0.19.0"
url = "2.5.0"
serde = { version = "1.0.197", features = ["serde_derive"], optional = true }
serde-wasm-bindgen = { version = "0.6.5", optional = true }
wasm-bindgen = { version = "0.2.92", optional = true }
reqwest =  { version = "0.12.0", optional = true } 
# to patch getrandom for wasm
getrandom = { version = "0.2.12", features = ["js"] }