[package]
name = "flipkart_scraper"
description = "Scrape Flipkart product details"
version = "0.1.141"
edition = "2021"
license = "GPL-3.0"
repository = "https://github.com/dvishal485/flipkart-scraper"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = ["serde"]
fetch = ["reqwest"]

[dependencies]
eyre = "0.6.12"
reqwest =  { version = "0.12.0", optional = true} 
scraper = "0.19.0"
serde = { version = "1.0.197", features = ["serde_derive"], optional = true }
url = "2.5.0"
